# Generated by Django 4.2.11 on 2024-09-24 11:22

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_project_date_alter_project_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, quality=85, scale=None, size=[250, 250], upload_to='images/'),
        ),
    ]
