# Generated by Django 4.2.11 on 2024-09-24 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_alter_project_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='source',
            field=models.CharField(default='https://github.com/MissBellum', max_length=100),
        ),
    ]
